version: '3'
services: 
    app:
        build: .
        ports:
            - "8080:8000"
        container_name: django_app
        command: python manage.py runserver 0.0.0.0:8000
    broker:
        image: rabbitmq:3.8.9-alpine
        ports:
            - 5673:5672
        container_name: rabbitmq_
    nextflow:
        image: nextflow/nextflow:latest
        container_name: nextflow_
        command: ./usr/local/bin/nextflow run hello