# Generated by Django 3.1.2 on 2020-11-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument', models.CharField(max_length=100)),
                ('eval_str', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='author',
        ),
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
        migrations.AddField(
            model_name='workflow',
            name='tasks',
            field=models.ManyToManyField(to='workflows.Task'),
        ),
    ]
