# Generated by Django 3.1.2 on 2020-10-14 21:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('notes', models.CharField(max_length=1000)),
                ('script_path', models.FilePathField()),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ready', 'Ready to run'), ('running', 'Running right now'), ('halted', 'Halted running'), ('in_queue', 'Waiting in queue'), ('skipped', 'Skipped running'), ('failed', 'Failed to run')], default='ready', max_length=32)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('notes', models.CharField(max_length=1000)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ready', 'Ready to run'), ('running', 'Running right now'), ('halted', 'Halted running'), ('in_queue', 'Waiting in queue'), ('skipped', 'Skipped running'), ('failed', 'Failed to run')], default='ready', max_length=32)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('notes', models.CharField(max_length=1000)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ready', 'Ready to run'), ('running', 'Running right now'), ('halted', 'Halted running'), ('in_queue', 'Waiting in queue'), ('skipped', 'Skipped running'), ('failed', 'Failed to run')], default='ready', max_length=32)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subtasks', models.ManyToManyField(to='workflows.Subtask')),
            ],
        ),
    ]
